bello:
  qq: qq,
simbot:
  core:
    # ????QQ????????:???
    bots: qq:qq密码
  component:
    mirai:
      # mirai????. ?????????????. ?????
      heartbeat-period-millis: 30000
      # ????????????.??????, ?????????? (???? 1s). ???????? (?????) ?????, ??????????.
      heartbeat-timeout-millis: 5000
      # ?????????????????.
      first-reconnect-delay-millis: 5000
      # ?????, ???????????
      reconnect-period-millis: 5000
      # ?????????
      reconnection-retry-times: 2147483647
      # ??????????????? net.mamoe.mirai.utils.BotConfiguration.MiraiProtocol ?????
      # ?????ANDROID_PHONE?ANDROID_PAD?ANDROID_WATCH
      protocol: ANDROID_PAD
      # ????mirai?bot logger
      no-bot-log: true
      # ??mirai????
      no-network-log: true
      # mirai bot log????simbot?log
      use-simbot-bot-log: true
      # mirai ??log ????simbot?log
      use-simbot-network-log: true
      # mirai?????deviceInfoSeed??????????????1.
      device-info-seed: 1
      # mirai?????????? love.forte.simbot.component.mirai.configuration.MiraiCacheType ?????
      # ??? FILE? MEMORY
      cache-type: MEMORY
      # ????? simbot.mirai.cacheType ??? FILE????????????????????????????
      cache-directory:
      # ????????????????????????????
      login-solver-type: DEFAULT
      # ?????????????? deviceInfo ? json?????
      dispatcher:
        # mirai????????????????????????
        core-pool-size: 8
        # mirai????????????????????????
        maximum-pool-size: 8
        # mirai????????????????????????????
        keep-alive-time: 1000
